import type { Metadata } from "next";
import "./globals.css";
import { Commissioner } from "next/font/google";

const commissionerFont = Commissioner({
  weight: ["400"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${commissionerFont.className}`}
      >
        {children}
      </body>
    </html>
  );
}
